Card componenti oluşturuldu.
burakcihan61/reactjs-themovie pull request #15
Opened 2023-01-30 22:01 UTC by burakcihan61

2023-01-31 14:43 UTC, adeministratorTr commented on src/components/Card/Card.tsx
> +      const result = await axios(
bu API call olayını services/movie.ts ya da benzer bi yere alıp, sayfadan ayıralım

2023-01-31 14:45 UTC, adeministratorTr commented on src/components/Card/Card.tsx
> +      {movies.map((movie: Result) => {
burada her bir movie için type belirtiyorsak, onun ismini daha spesifik verelim. Result birazcık API'dan dönen tüm response için gibi duruyor.

2023-01-31 14:47 UTC, adeministratorTr commented on src/components/Card/Card.tsx
> +          <div key={movie.id} className={styles.movie}>
Belki bu PR onun yeri değil, ama ileride buraya bi Loading indicator da koyabiliriz.

2023-01-31 14:47 UTC, adeministratorTr commented on .env
> +REACT_APP_API_KEY=
`.env` dosyasını .gitignore'da koyabiliriz.

2023-01-31 14:48 UTC, adeministratorTr requested changes
Yorumlardan kafana yatmayan/doğru gelmeyen/nedeni anlaşılmayan varsa konuşalım.

2023-01-31 16:15 UTC, burakcihan61 commented on .env
> +REACT_APP_API_KEY=
burada gitignore dosyam olduğu halde .env uzantılarımı git add dediğim zaman içeri alıyor

2023-02-02 16:26 UTC, adeministratorTr commented on src/services/movie.ts
> +    return data.results;
services kısmında herhangi bi şekilde filtreleme, gelen datayı daraltma vs yapmayalım. Buranın tek görevi istek atıp, gelen veriyi dönmek olsun.

Gelen veriden ilgili kısmı set etmeyi kullandığımız sayfa içinde, redux/context gibi yerlerde yapalım. Şuan ihtiyacımız yok ama ileride gelen response'taki statusCode vs gibi şeylere ihtiyacımız olabilir.

2023-02-02 16:27 UTC, adeministratorTr commented on src/components/Content/Content.tsx
> +          movies.map((movie: TMovieCard) => {
```suggestion
movies.map((movie: TMovieCard) => {
            return (
```

yerine 

```suggestion
movies.map((movie: TMovieCard) => (
```

şeklinde de kullanabilirsin. Zorun değil

2023-02-02 16:28 UTC, adeministratorTr commented on src/components/Card/Card.tsx
> +          src={`${process.env.REACT_APP_IMAGE_URL}${props.moviePosterPath}`}
Geçen bahsettiğimiz sebeplerden ötürü, bu resimlerin url'ini burda değil, bu image prop'unu verdiğimiz yerde set edelim. Başka sayfada başka IMAGE URL ile set etmemiz gerekebilir

2023-02-02 16:29 UTC, adeministratorTr commented on src/components/Card/Card.tsx
> +  moviePosterPath?: string;
Eğer `moviePosterPath` opsiyonel ise, kullandığımız yerde var mı diye kontrol edebiliriz, yoksa default value verebiliriz

2023-02-02 18:15 UTC, burakcihan61 commented on src/services/movie.ts
> +    return data.results;
data filtresiz hala getirildi.

2023-02-02 18:20 UTC, burakcihan61 commented on src/components/Content/Content.tsx
> +          movies.map((movie: TMovieCard) => {
return kaldırıldı, () ile return elde edildi.

2023-02-02 18:30 UTC, burakcihan61 commented on src/components/Card/Card.tsx
> +          src={`${process.env.REACT_APP_IMAGE_URL}${props.moviePosterPath}`}
Image props düzenlendi. Prop verdiğimiz yerde set edildi.

2023-02-02 18:31 UTC, burakcihan61 commented on src/components/Card/Card.tsx
> +  moviePosterPath?: string;
Opsiyonel değil düzenleme yapıldı. Zorunla hale getirildi.

2023-02-02 18:33 UTC, merged